'use client';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';

const faqs = [
  {
    question: 'What makes this AI headshot generator different from others?',
    answer: 'Our AI headshot generator focuses on speed, realism, and privacy. We offer three professional background styles (Corporate Gray, Modern Tech Blue, Bright Daylight White) that cover 80% of business scenarios. No clutter, just a direct path to professional photos in 90 seconds.',
  },
  {
    question: 'How long does it take to generate professional headshots?',
    answer: 'Our AI headshot generator processes your selfie in approximately 90 seconds, delivering three professional backgrounds instantly—much faster than traditional photography sessions that take days.',
  },
  {
    question: 'Is there a free trial for the AI headshot generator?',
    answer: 'Yes! You can test low-res previews before buying a full-res download from our AI headshot generator. This lets you see the quality before making any commitment.',
  },
  {
    question: 'What photo quality should I upload for best results?',
    answer: 'For optimal results with our AI headshot generator, upload a clear, well-lit selfie with your face centered and looking directly at the camera. Avoid heavy filters, sunglasses, or busy backgrounds. We accept JPG and PNG files up to 10 MB.',
  },
  {
    question: 'Do you store my photos after processing?',
    answer: 'No. Our AI headshot generator wipes all data after 24 hours by default. All uploads use end-to-end encryption, and we never use your photos to train AI models without explicit permission. Your privacy is our top priority.',
  },
  {
    question: 'What sizes and formats do I get when downloading?',
    answer: 'The AI headshot generator provides high-resolution 300 DPI files perfect for printing, plus auto-cropped versions optimized for LinkedIn (400×400), Slack (512×512), and Zoom (1280×720). No watermarks, completely royalty-free.',
  },
  {
    question: 'Which background style works best for my industry?',
    answer: 'Corporate Gray suits traditional business sectors like finance and law. Modern Tech Blue works great for startups and tech companies. Bright Daylight White is perfect for coaches, consultants, and creative professionals. Our AI headshot generator provides all three automatically.',
  },
  {
    question: 'Can I use these headshots for commercial purposes?',
    answer: 'Absolutely! All headshots generated by our AI headshot generator are royalty-free and can be used for any commercial purpose, including business websites, marketing materials, and professional profiles. Perfect for business cards and brochures too.',
  },
];

export default function FAQ() {
  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
        <div className="text-center mb-16">
          <Badge variant="outline" className="mb-6">FAQ</Badge>
          <h2 className="text-4xl font-bold mb-4">AI Headshot Generator FAQ - Professional Photo Guide</h2>
          <p className="text-lg text-muted-foreground">
            Questions about our AI headshot generator? Contact us at <a href="mailto:wendy.1031ht@gmail.com" className="text-[#a259ff] underline">wendy.1031ht@gmail.com</a>.
          </p>
        </div>

        <Accordion type="single" collapsible className="space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={faq.question}
              value={`item-${index}`}
              className="border border-gray-200 rounded-lg px-6"
            >
              <AccordionTrigger className="text-left hover:no-underline py-6">
                <div className="flex items-start gap-3">
                  <div className="bg-gray-100 text-gray-600 rounded-full w-6 h-6 flex items-center justify-center text-sm font-medium flex-shrink-0 mt-0.5">
                    {index + 1}
                  </div>
                  <span className="font-medium">{faq.question}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent className="pb-6 pl-9 text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
